package com.example.ui.theme

import androidx.compose.ui.graphics.Color
import com.example.model.ThemeMode

data class EditorColorScheme(
    val activityBarBackground: Color,
    val activityBarIconSelected: Color,
    val activityBarIconUnselected: Color,
    val sidebarBackground: Color,
    val sidebarText: Color,
    val editorBackground: Color,
    val editorGutterBackground: Color,
    val editorLineNumber: Color,
    val editorActiveLine: Color,
    val editorTextColor: Color,
    val tabBarBackground: Color,
    val tabActiveBackground: Color,
    val tabInactiveBackground: Color,
    val statusBarBackground: Color,
    val statusBarText: Color,
    val keywordColor: Color,
    val stringColor: Color,
    val commentColor: Color,
    val numberColor: Color,
    val functionColor: Color,
    val typeColor: Color,
    val accentColor: Color,
    val warningColor: Color = Color(0xFFFFB300)
)

fun getThemePalette(mode: ThemeMode): EditorColorScheme {
    return when (mode) {
        ThemeMode.VS_CODE_DARK -> EditorColorScheme(
            activityBarBackground = Color(0xFF333333),
            activityBarIconSelected = Color(0xFFFFFFFF),
            activityBarIconUnselected = Color(0xFF858585),
            sidebarBackground = Color(0xFF252526),
            sidebarText = Color(0xFFCCCCCC),
            editorBackground = Color(0xFF1E1E1E),
            editorGutterBackground = Color(0xFF1E1E1E),
            editorLineNumber = Color(0xFF858585),
            editorActiveLine = Color(0xFF282828),
            editorTextColor = Color(0xFFD4D4D4),
            tabBarBackground = Color(0xFF252526),
            tabActiveBackground = Color(0xFF1E1E1E),
            tabInactiveBackground = Color(0xFF2D2D2D),
            statusBarBackground = Color(0xFF007ACC),
            statusBarText = Color(0xFFFFFFFF),
            keywordColor = Color(0xFF569CD6),
            stringColor = Color(0xFFCE9178),
            commentColor = Color(0xFF6A9955),
            numberColor = Color(0xFFB5CEA8),
            functionColor = Color(0xFFDCDCAA),
            typeColor = Color(0xFF4EC9B0),
            accentColor = Color(0xFF007ACC)
        )
        ThemeMode.MONOKAI_PRO -> EditorColorScheme(
            activityBarBackground = Color(0xFF19181A),
            activityBarIconSelected = Color(0xFFFFD866),
            activityBarIconUnselected = Color(0xFF727072),
            sidebarBackground = Color(0xFF222125),
            sidebarText = Color(0xFFC1C0C0),
            editorBackground = Color(0xFF2D2A2E),
            editorGutterBackground = Color(0xFF2D2A2E),
            editorLineNumber = Color(0xFF727072),
            editorActiveLine = Color(0xFF3A373B),
            editorTextColor = Color(0xFFFCFCFA),
            tabBarBackground = Color(0xFF222125),
            tabActiveBackground = Color(0xFF2D2A2E),
            tabInactiveBackground = Color(0xFF19181A),
            statusBarBackground = Color(0xFFFF6188),
            statusBarText = Color(0xFF2D2A2E),
            keywordColor = Color(0xFFFF6188),
            stringColor = Color(0xFFFFD866),
            commentColor = Color(0xFF727072),
            numberColor = Color(0xFFAB9DF2),
            functionColor = Color(0xFFA9DC76),
            typeColor = Color(0xFF78DCE8),
            accentColor = Color(0xFFFFD866)
        )
        ThemeMode.ONE_DARK_PRO -> EditorColorScheme(
            activityBarBackground = Color(0xFF21252B),
            activityBarIconSelected = Color(0xFF61AFEF),
            activityBarIconUnselected = Color(0xFF5C6370),
            sidebarBackground = Color(0xFF21252B),
            sidebarText = Color(0xFFABB2BF),
            editorBackground = Color(0xFF282C34),
            editorGutterBackground = Color(0xFF282C34),
            editorLineNumber = Color(0xFF4B5263),
            editorActiveLine = Color(0xFF2C313C),
            editorTextColor = Color(0xFFABB2BF),
            tabBarBackground = Color(0xFF21252B),
            tabActiveBackground = Color(0xFF282C34),
            tabInactiveBackground = Color(0xFF21252B),
            statusBarBackground = Color(0xFF61AFEF),
            statusBarText = Color(0xFF21252B),
            keywordColor = Color(0xFFC678DD),
            stringColor = Color(0xFF98C379),
            commentColor = Color(0xFF5C6370),
            numberColor = Color(0xD6D19A66),
            functionColor = Color(0xFF61AFEF),
            typeColor = Color(0xFFE5C07B),
            accentColor = Color(0xFF61AFEF)
        )
        ThemeMode.DRACULA -> EditorColorScheme(
            activityBarBackground = Color(0xFF1E1F29),
            activityBarIconSelected = Color(0xFFFF79C6),
            activityBarIconUnselected = Color(0xFF6272A4),
            sidebarBackground = Color(0xFF21222C),
            sidebarText = Color(0xFFF8F8F2),
            editorBackground = Color(0xFF282A36),
            editorGutterBackground = Color(0xFF282A36),
            editorLineNumber = Color(0xFF6272A4),
            editorActiveLine = Color(0xFF44475A),
            editorTextColor = Color(0xFFF8F8F2),
            tabBarBackground = Color(0xFF1E1F29),
            tabActiveBackground = Color(0xFF282A36),
            tabInactiveBackground = Color(0xFF21222C),
            statusBarBackground = Color(0xFFBD93F9),
            statusBarText = Color(0xFF282A36),
            keywordColor = Color(0xFFFF79C6),
            stringColor = Color(0xFFF1FA8C),
            commentColor = Color(0xFF6272A4),
            numberColor = Color(0xFFBD93F9),
            functionColor = Color(0xFF50FA7B),
            typeColor = Color(0xFF8BE9FD),
            accentColor = Color(0xFFFF79C6)
        )
        ThemeMode.SOLARIZED_DARK -> EditorColorScheme(
            activityBarBackground = Color(0xFF00141A),
            activityBarIconSelected = Color(0xFF2AA198),
            activityBarIconUnselected = Color(0xFF586E75),
            sidebarBackground = Color(0xFF073642),
            sidebarText = Color(0xFF839496),
            editorBackground = Color(0xFF002B36),
            editorGutterBackground = Color(0xFF002B36),
            editorLineNumber = Color(0xFF586E75),
            editorActiveLine = Color(0xFF073642),
            editorTextColor = Color(0xFF839496),
            tabBarBackground = Color(0xFF073642),
            tabActiveBackground = Color(0xFF002B36),
            tabInactiveBackground = Color(0xFF00141A),
            statusBarBackground = Color(0xFF268BD2),
            statusBarText = Color(0xFFFDF6E3),
            keywordColor = Color(0xFF859900),
            stringColor = Color(0xFF2AA198),
            commentColor = Color(0xFF586E75),
            numberColor = Color(0xFFD33682),
            functionColor = Color(0xFF268BD2),
            typeColor = Color(0xFFCB4B16),
            accentColor = Color(0xFF2AA198)
        )
        ThemeMode.GITHUB_LIGHT -> EditorColorScheme(
            activityBarBackground = Color(0xFFF6F8FA),
            activityBarIconSelected = Color(0xFF0969DA),
            activityBarIconUnselected = Color(0xFF57606A),
            sidebarBackground = Color(0xFFF6F8FA),
            sidebarText = Color(0xFF24292F),
            editorBackground = Color(0xFFFFFFFF),
            editorGutterBackground = Color(0xFFFFFFFF),
            editorLineNumber = Color(0xFF8C959F),
            editorActiveLine = Color(0xFFF6F8FA),
            editorTextColor = Color(0xFF24292F),
            tabBarBackground = Color(0xFFF6F8FA),
            tabActiveBackground = Color(0xFFFFFFFF),
            tabInactiveBackground = Color(0xFFEAEEF2),
            statusBarBackground = Color(0xFF0969DA),
            statusBarText = Color(0xFFFFFFFF),
            keywordColor = Color(0xFFCF222E),
            stringColor = Color(0xFF0A3069),
            commentColor = Color(0xFF6E7781),
            numberColor = Color(0xFF0550AE),
            functionColor = Color(0xFF8250DF),
            typeColor = Color(0xFF953800),
            accentColor = Color(0xFF0969DA)
        )
    }
}
