package com.example.network

import com.example.BuildConfig
import com.example.model.ProposedChangeType
import com.example.model.ProposedFileChange
import com.example.model.ProposedWorkspaceEdit
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

object GeminiService {
    private const val BASE_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent"

    private val client = OkHttpClient.Builder()
        .connectTimeout(60, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .build()

    suspend fun generateWorkspaceResponse(
        prompt: String,
        workspaceContext: String,
        actionType: String = "chat"
    ): Pair<String, ProposedWorkspaceEdit?> = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext Pair("⚠️ Gemini API key is missing or not configured. Please add your key in the AI Studio Secrets panel.", null)
        }

        val systemPrompt = when (actionType) {
            "explain" -> "Analyze the provided project workspace context and explain the architecture, functions, and relationships clearly with bullet points:"
            "fix" -> "Analyze the entire workspace context for bugs, compile issues, or anti-patterns. Propose precise file edits to fix them."
            "refactor" -> "Analyze the workspace and refactor code across multiple files for performance, clean architecture, and modularity."
            "test" -> "Analyze the workspace files and generate comprehensive unit tests."
            "audit" -> "Audit the workspace for security vulnerabilities, dead code, unused imports, and performance bottlenecks."
            else -> "You are VS Code AI Copilot with full workspace awareness. Help the user answer questions, refactor, search, and edit files across the project."
        }

        val fullPrompt = StringBuilder()
        fullPrompt.append(systemPrompt).append("\n\n")
        fullPrompt.append(workspaceContext).append("\n\n")
        fullPrompt.append("User Query: ").append(prompt)

        try {
            val jsonPayload = JSONObject().apply {
                val contentsArray = JSONArray().apply {
                    val contentObj = JSONObject().apply {
                        val partsArray = JSONArray().apply {
                            val partObj = JSONObject().apply {
                                put("text", fullPrompt.toString())
                            }
                            put(partObj)
                        }
                        put("parts", partsArray)
                    }
                    put(contentObj)
                }
                put("contents", contentsArray)
            }

            val requestBody = jsonPayload.toString().toRequestBody("application/json".toMediaType())
            val request = Request.Builder()
                .url("$BASE_URL?key=$apiKey")
                .post(requestBody)
                .build()

            client.newCall(request).execute().use { response ->
                if (!response.isSuccessful) {
                    return@withContext Pair("Error calling Gemini API (HTTP ${response.code}): ${response.message}", null)
                }

                val responseStr = response.body?.string() ?: return@withContext Pair("Empty response from Gemini AI.", null)
                val jsonResponse = JSONObject(responseStr)
                val candidates = jsonResponse.optJSONArray("candidates")
                if (candidates != null && candidates.length() > 0) {
                    val candidate = candidates.getJSONObject(0)
                    val content = candidate.optJSONObject("content")
                    val parts = content?.optJSONArray("parts")
                    if (parts != null && parts.length() > 0) {
                        val rawText = parts.getJSONObject(0).optString("text", "No text generated.")
                        val proposedEdit = parseProposedWorkspaceEdit(rawText)
                        val cleanText = cleanRawResponseText(rawText)
                        return@withContext Pair(cleanText, proposedEdit)
                    }
                }
                Pair("No output generated by Gemini model.", null)
            }
        } catch (e: Exception) {
            Pair("Error interacting with Gemini AI: ${e.localizedMessage ?: e.message}", null)
        }
    }

    private fun parseProposedWorkspaceEdit(rawText: String): ProposedWorkspaceEdit? {
        val editRegex = "<workspace_edit\\s+title=\"([^\"]+)\"\\s+confidence=\"(\\d+)\"\\s+explanation=\"([^\"]+)\">([\\s\\S]*?)</workspace_edit>".toRegex()
        val match = editRegex.find(rawText) ?: return null

        val title = match.groupValues[1]
        val confidence = match.groupValues[2].toIntOrNull() ?: 95
        val explanation = match.groupValues[3]
        val body = match.groupValues[4]

        val fileEditRegex = "<file_edit\\s+path=\"([^\"]+)\"\\s+type=\"([^\"]+)\">([\\s\\S]*?)</file_edit>".toRegex()
        val fileChanges = mutableListOf<ProposedFileChange>()

        fileEditRegex.findAll(body).forEach { fMatch ->
            val path = fMatch.groupValues[1]
            val typeStr = fMatch.groupValues[2].uppercase()
            val innerBody = fMatch.groupValues[3].trim()

            // Extract code inside markdown code block if present
            val codeRegex = "```[a-zA-Z]*\\n([\\s\\S]*?)```".toRegex()
            val codeMatch = codeRegex.find(innerBody)
            val newContent = codeMatch?.groupValues?.get(1)?.trim() ?: innerBody

            val changeType = when (typeStr) {
                "CREATE" -> ProposedChangeType.CREATE_FILE
                "DELETE" -> ProposedChangeType.DELETE_FILE
                "RENAME" -> ProposedChangeType.RENAME_FILE
                else -> ProposedChangeType.EDIT_FILE
            }

            fileChanges.add(
                ProposedFileChange(
                    filePath = path,
                    changeType = changeType,
                    newContent = newContent,
                    explanation = "AI proposed $changeType for $path"
                )
            )
        }

        if (fileChanges.isEmpty()) return null

        return ProposedWorkspaceEdit(
            title = title,
            confidenceScore = confidence,
            explanation = explanation,
            fileChanges = fileChanges
        )
    }

    private fun cleanRawResponseText(rawText: String): String {
        return rawText.replace("<workspace_edit[\\s\\S]*?</workspace_edit>".toRegex(), "").trim()
    }
}
