package com.example.network

import com.example.BuildConfig
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

object GeminiService {
    private const val BASE_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent"

    private val client = OkHttpClient.Builder()
        .connectTimeout(60, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .build()

    suspend fun generateCodeAssistantResponse(
        prompt: String,
        activeCode: String? = null,
        language: String? = null,
        actionType: String = "chat"
    ): String = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext "⚠️ Gemini API key is missing or not configured. Please add your key in the AI Studio Secrets panel."
        }

        val systemPrompt = when (actionType) {
            "explain" -> "You are VS Code AI Copilot. Explain the following $language code concisely with clear bullet points:"
            "fix" -> "You are VS Code AI Copilot. Identify any bugs, errors, or anti-patterns in this $language code and provide the fixed working version:"
            "refactor" -> "You are VS Code AI Copilot. Refactor this $language code for cleaner architecture, performance, and readability:"
            "test" -> "You are VS Code AI Copilot. Generate comprehensive unit tests for this $language code:"
            "translate" -> "You are VS Code AI Copilot. Translate this code to clean $language:"
            else -> "You are VS Code AI Copilot integrated into Code Studio Android IDE. Answer developer queries, provide clean code snippets, and assist with debugging."
        }

        val fullPrompt = StringBuilder()
        fullPrompt.append(systemPrompt).append("\n\n")
        if (!activeCode.isNull_or_empty()) {
            fullPrompt.append("```$language\n").append(activeCode).append("\n```\n\n")
        }
        fullPrompt.append("User Query: ").append(prompt)

        try {
            val jsonPayload = JSONObject().apply {
                val contentsArray = JSONArray().apply {
                    val contentObj = JSONObject().apply {
                        val partsArray = JSONArray().apply {
                            val partObj = JSONObject().apply {
                                put("text", fullPrompt.toString())
                            }
                            put(partObj)
                        }
                        put("parts", partsArray)
                    }
                    put(contentObj)
                }
                put("contents", contentsArray)
            }

            val requestBody = jsonPayload.toString().toRequestBody("application/json".toMediaType())
            val request = Request.Builder()
                .url("$BASE_URL?key=$apiKey")
                .post(requestBody)
                .build()

            client.newCall(request).execute().use { response ->
                if (!response.isSuccessful) {
                    return@withContext "Error calling Gemini API (HTTP ${response.code}): ${response.message}"
                }

                val responseStr = response.body?.string() ?: return@withContext "Empty response from Gemini AI."
                val jsonResponse = JSONObject(responseStr)
                val candidates = jsonResponse.optJSONArray("candidates")
                if (candidates != null && candidates.length() > 0) {
                    val candidate = candidates.getJSONObject(0)
                    val content = candidate.optJSONObject("content")
                    val parts = content?.optJSONArray("parts")
                    if (parts != null && parts.length() > 0) {
                        return@withContext parts.getJSONObject(0).optString("text", "No text generated.")
                    }
                }
                "No output generated by Gemini model."
            }
        } catch (e: Exception) {
            "Error interacting with Gemini AI: ${e.localizedMessage ?: e.message}"
        }
    }
}

private fun String?.isNull_or_empty(): Boolean = this == null || this.isEmpty()
